/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Blockout11.glb -o src/components/Blockout11.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Environment(props) {
  const { nodes, materials } = useGLTF('./Blockout11.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[10.883, 3.001, 58.261]} rotation={[0, -1.28, 0]} scale={0.646}>
        <mesh geometry={nodes.ContainerContainer.geometry} material={nodes.ContainerContainer.material} position={[0, -0.37, 0]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.ContainerDecals.geometry} material={nodes.ContainerDecals.material} position={[0, -0.988, 0]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.ContainerDoors.geometry} material={nodes.ContainerDoors.material} position={[0, -0.87, 0]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes.ContainerLocks.geometry} material={nodes.ContainerLocks.material} position={[0, -0.842, 0]} rotation={[0, -1.571, 0]} />
      </group>
      <group position={[7.655, 3.001, 42.607]} scale={5.617}>
        <mesh geometry={nodes.wifi_symbol.geometry} material={nodes.wifi_symbol.material} position={[-0.062, -0.192, 0]} />
      </group>
      {/* Bike geometry - now used in separate Bike.jsx component for drivable vehicle */}
      {/* <group position={[0.026, 0, -5.604]}>
        <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} />
        <mesh geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} />
        <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
        <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
        <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
        <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} />
        <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} />
        <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} />
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} />
        <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} />
        <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} />
        <mesh geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} />
        <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} />
        <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} />
        <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} />
        <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} />
        <mesh geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} />
        <mesh geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} />
        <mesh geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} />
        <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
        <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
        <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} />
        <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} />
        <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} />
        <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} />
        <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} />
        <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} />
        <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} />
        <mesh geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} />
        <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} />
        <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} />
        <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} />
        <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} />
        <mesh geometry={nodes.Cylinder017.geometry} material={nodes.Cylinder017.material} />
        <mesh geometry={nodes.Cylinder018.geometry} material={nodes.Cylinder018.material} />
        <mesh geometry={nodes.Cylinder019.geometry} material={nodes.Cylinder019.material} />
        <mesh geometry={nodes.Cylinder020.geometry} material={nodes.Cylinder020.material} />
        <mesh geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} />
        <mesh geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} />
        <mesh geometry={nodes.Cylinder023.geometry} material={nodes.Cylinder023.material} />
        <mesh geometry={nodes.Cylinder025.geometry} material={nodes.Cylinder025.material} />
        <mesh geometry={nodes.Cylinder026.geometry} material={nodes.Cylinder026.material} />
        <mesh geometry={nodes.Cylinder027.geometry} material={nodes.Cylinder027.material} />
        <mesh geometry={nodes.Cylinder028.geometry} material={nodes.Cylinder028.material} />
        <mesh geometry={nodes.Cylinder029.geometry} material={nodes.Cylinder029.material} />
        <mesh geometry={nodes.Cylinder030.geometry} material={nodes.Cylinder030.material} />
        <mesh geometry={nodes.Cylinder031.geometry} material={nodes.Cylinder031.material} />
        <mesh geometry={nodes.Cylinder032.geometry} material={nodes.Cylinder032.material} />
        <mesh geometry={nodes.Cylinder033.geometry} material={nodes.Cylinder033.material} />
        <mesh geometry={nodes.Cylinder034.geometry} material={nodes.Cylinder034.material} />
        <mesh geometry={nodes.Cylinder035.geometry} material={nodes.Cylinder035.material} />
        <mesh geometry={nodes.Cylinder036.geometry} material={nodes.Cylinder036.material} />
        <mesh geometry={nodes.Cylinder037.geometry} material={nodes.Cylinder037.material} />
        <mesh geometry={nodes.Cylinder038.geometry} material={nodes.Cylinder038.material} />
        <mesh geometry={nodes.Cylinder039.geometry} material={nodes.Cylinder039.material} />
        <mesh geometry={nodes.Cylinder040.geometry} material={nodes.Cylinder040.material} />
        <mesh geometry={nodes.NurbsPath.geometry} material={nodes.NurbsPath.material} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={nodes.NurbsPath001.material} />
        <mesh geometry={nodes.NurbsPath002.geometry} material={nodes.NurbsPath002.material} />
        <mesh geometry={nodes.NurbsPath003.geometry} material={nodes.NurbsPath003.material} />
        <mesh geometry={nodes.NurbsPath004.geometry} material={nodes.NurbsPath004.material} />
        <mesh geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
        <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
        <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
        <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
        <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
        <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
        <mesh geometry={nodes.Object_16.geometry} material={nodes.Object_16.material} />
        <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
        <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
        <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
        <mesh geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
        <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
        <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
        <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
        <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
        <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
        <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
        <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
        <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
        <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
        <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
        <mesh geometry={nodes.Object_3.geometry} material={nodes.Object_3.material} />
        <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
        <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
        <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
        <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
        <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
        <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
        <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
        <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
        <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} />
        <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
        <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} />
        <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} />
        <mesh geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} />
        <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} />
        <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} />
        <mesh geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} />
        <mesh geometry={nodes.Torus002.geometry} material={nodes.Torus002.material} />
      </group> */}
      <mesh geometry={nodes.Tractor.geometry} material={nodes.Tractor.material} position={[-15.387, 2.994, 69.542]} rotation={[Math.PI / 2, 0, -2.156]} scale={0.027} />
      <mesh geometry={nodes['Traffic_Cone_(Photoscanned)'].geometry} material={nodes['Traffic_Cone_(Photoscanned)'].material} position={[-9.733, 2.206, 44.881]} scale={3.195} />
      <mesh geometry={nodes.Curve005.geometry} material={nodes.Curve005.material} position={[15.41, 1.702, 78.369]} rotation={[1.441, 0.034, 2.676]} scale={30.703} />
      <mesh geometry={nodes.Curve004.geometry} material={nodes.Curve004.material} position={[15.465, 1.698, 78.478]} rotation={[1.441, 0.034, 2.676]} scale={30.703} />
      <mesh geometry={nodes.Curve003.geometry} material={nodes.Curve003.material} position={[15.52, 1.697, 78.586]} rotation={[1.441, 0.034, 2.676]} scale={30.703} />
      <mesh geometry={nodes.Curve002.geometry} material={nodes.Curve002.material} position={[15.52, 1.764, 78.586]} rotation={[1.441, 0.034, 2.676]} scale={30.703} />
      <mesh geometry={nodes.Curve001.geometry} material={nodes.Curve001.material} position={[15.52, 1.766, 78.586]} rotation={[1.441, 0.034, 2.676]} scale={30.703} />
      <mesh geometry={nodes.Curve.geometry} material={nodes.Curve.material} position={[15.52, 1.657, 78.586]} rotation={[1.441, 0.034, 2.676]} scale={30.703} />
      <mesh geometry={nodes.Snowboard2.geometry} material={nodes.Snowboard2.material} position={[-6.453, 2.994, 23.993]} rotation={[0.912, -0.011, 0.449]} scale={2.184} />
      <mesh geometry={nodes.Skateboard.geometry} material={nodes.Skateboard.material} position={[5.2, 3.024, 17.96]} rotation={[0, -0.833, -1.386]} scale={2.133} />
      <mesh geometry={nodes.gogo_inflight.geometry} material={nodes.gogo_inflight.material} position={[10.893, 0.415, 42.081]} rotation={[1.317, 0.073, 2.868]} />
      <mesh geometry={nodes.life_fitness.geometry} material={nodes.life_fitness.material} position={[-10.079, 0.42, 67.705]} rotation={[1.313, -0.056, -2.932]} />
      <mesh geometry={nodes.FourKites.geometry} material={nodes.FourKites.material} position={[15.43, 0.41, 76.655]} rotation={[1.602, 0.042, 2.848]} />
      <mesh geometry={nodes.FA_Skates.geometry} material={nodes.FA_Skates.material} position={[7.284, 0.309, 17.617]} rotation={[1.317, 0.071, 2.874]} />
      <mesh geometry={nodes.Chillorg.geometry} material={nodes.Chillorg.material} position={[-4.914, 0.415, 25.117]} rotation={[1.334, -0.118, -2.687]} />
      <mesh geometry={nodes.Thios.geometry} material={nodes.Thios.material} position={[13.094, 0.4, 57.573]} rotation={[1.602, 0.042, 2.848]} />
      <mesh geometry={nodes.HERE.geometry} material={nodes.HERE.material} position={[-7.988, 0.308, 46.766]} rotation={[1.356, -0.154, -2.53]} />
    </group>
  )
}

useGLTF.preload('./Blockout11.glb')
