/* Auto-generated by: https://github.com/pmndrs/gltfjsx */
import React from 'react'
import { useGLTF } from '@react-three/drei'
// import { useTrimesh } from '@react-three/cannon'

const Collidable = ({ geometry, ...props }) => {
  // useTrimesh(() => ({ args: [geometry.attributes.position.array, geometry.index.array], type: 'Static', ...props }))
  return <mesh geometry={geometry} {...props} />
}

export function Bike(props) {
  const { nodes, materials } = useGLTF('/Blockout8-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials['Air Duct Rubber']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Dark Steel']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Dark Brown Leather']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder026.geometry} material={materials.PaletteMaterial013} />
      <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.AppE8} />
      <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.AppED} />
      <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.AppCD} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere.geometry} material={materials['Expanded Steel']} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={materials.PaletteMaterial014} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere002.geometry} material={materials.PaletteMaterial015} />
    </group>
  )
}

export function Environment(props) {
  const { nodes, materials } = useGLTF('/Blockout8-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <Collidable castShadow receiveShadow geometry={nodes.ramp.geometry} material={materials.PaletteMaterial001} position={[17.835, 0.964, -25.903]} rotation={[0, 1.571, 0]} scale={[0.212, 0.088, 0.102]} />
      <mesh castShadow receiveShadow geometry={nodes['01d_-_frame_-_'].geometry} material={materials['Green matte metal']} position={[7.669, 1.68, -10.467]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.plinth_2.geometry} material={materials['Dark wood']} position={[7.669, 1.684, -10.467]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.brep_1.geometry} material={materials.PaletteMaterial002} position={[8.311, 1.582, -9.866]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes['Humano_Posed_0341842-Man_01_LOD1'].geometry} material={nodes['Humano_Posed_0341842-Man_01_LOD1'].material} position={[7.573, 0.681, -10.748]} rotation={[0, 0.16, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['01d_-_panel_-_inner001'].geometry} material={materials['Wood 45 Black Wall Panelling']} position={[7.667, 1.665, -10.461]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes['01d_-_panel_-_outer001'].geometry} material={materials.PaletteMaterial003} position={[7.667, 1.665, -10.461]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes['05a_-_inner_-_panel001'].geometry} material={materials['Glass Orange']} position={[7.667, 1.665, -10.461]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Solid_2169002.geometry} material={materials.PaletteMaterial004} position={[7.667, 1.665, -10.461]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Solid_2269002.geometry} material={materials.PaletteMaterial005} position={[7.667, 1.665, -10.461]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Solid_2190002.geometry} material={materials.PaletteMaterial006} position={[7.667, 1.665, -10.461]} rotation={[-Math.PI, 1.565, -Math.PI]} />
      <Collidable castShadow receiveShadow geometry={nodes.pavement001.geometry} material={materials['Asphalt.002']} position={[3.656, 0.013, -0.058]} rotation={[0, 0.003, 0]} scale={[2.002, 1, 2.411]} />
      <Collidable castShadow receiveShadow geometry={nodes.Skate_Park_Photoscan_2.geometry} material={materials.skatepark_Sec2_u1_v1} position={[0.153, 0, 19.41]} rotation={[-Math.PI, 0.014, -Math.PI]} scale={1.161} />
      <Collidable castShadow receiveShadow geometry={nodes['Skate_Ramp_(Photoscanned)001'].geometry} material={materials['Skate Ramp (Photoscanned)']} position={[13.366, 0, -27.865]} />
      <Collidable castShadow receiveShadow geometry={nodes['Skate_Ramp_(Photoscanned)'].geometry} material={materials.SkateRamp} position={[-7.578, 0, 28.091]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Snowboard2.geometry} material={materials.PaletteMaterial010} position={[-0.038, 1.268, -0.285]} rotation={[0.912, -0.011, 0.449]} scale={2.184} />
      <mesh castShadow receiveShadow geometry={nodes.Skateboard.geometry} material={materials.skateboard} position={[-2.227, 1.69, -12.139]} rotation={[0, -0.833, -1.386]} scale={2.133} />
      <mesh castShadow receiveShadow geometry={nodes.SketchUp003.geometry} material={materials.PaletteMaterial007} position={[19.918, 0, 8.598]} rotation={[0, -1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.SketchUp005.geometry} material={materials.PaletteMaterial009} position={[19.918, 0, 8.598]} rotation={[0, -1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.FourKites.geometry} material={materials.color} position={[17.312, 1.175, 12.084]} rotation={[1.695, 0.233, 1.076]} />
      <Collidable castShadow receiveShadow geometry={nodes.floor_paint001.geometry} material={materials.PaletteMaterial008} position={[-7.449, 0.018, 22.543]} />
      <mesh castShadow receiveShadow geometry={nodes.Wooden_sitting.geometry} material={materials['Stained bamboo']} position={[7.34, 0.693, -9.876]} rotation={[0, Math.PI / 2, 0]} scale={[0.331, 1, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.group_0.geometry} material={materials['Material.045']} position={[9.508, 0.036, -9.104]} rotation={[0, Math.PI / 2, 0]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.group_1.geometry} material={materials['Black matte metal']} position={[9.449, 0.58, -9.447]} rotation={[0, Math.PI / 2, 0]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.instance_0.geometry} material={materials['Walnut Wood']} position={[9.818, 0.014, -11.179]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.023, 0.023, 0.066]} />
      <mesh castShadow receiveShadow geometry={nodes.base001.geometry} material={materials.PaletteMaterial011} position={[-15.137, 1.224, 2.676]} rotation={[2.269, 0.647, -2.499]} scale={8.783} />
      <mesh castShadow receiveShadow geometry={nodes.n64_emblem.geometry} material={materials.n64_emblem} position={[-14.94, 1.585, 2.52]} rotation={[2.269, 0.647, -2.499]} scale={8.783} />
      <group position={[-15.253, 2.887, 20.808]} rotation={[-0.347, 0.741, 0.531]} scale={0.055}>
        <mesh castShadow receiveShadow geometry={nodes.Plane011.geometry} material={materials['Scifi Grid 01']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane011_1.geometry} material={materials['Matal solid paint white']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.front_landing_gear.geometry} material={materials.PaletteMaterial012} position={[-14.356, 3.314, 21.763]} rotation={[-0.347, 0.741, 0.531]} scale={0.055} />
    </group>
  )
}

useGLTF.preload('/Blockout8-transformed.glb')
