/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Blockout9.glb --transform --keepnames 
Files: public/Blockout9.glb [23.86MB] > /Users/peterbartsch/Documents/GitHub/peterbartsch.com/folio-3d/Blockout9-transformed.glb [6.21MB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useTrimesh } from '@react-three/cannon'

const Collidable = ({ geometry, ...props }) => {
  // useTrimesh(() => ({ args: [geometry.attributes.position.array, geometry.index.array], type: 'Static', ...props }))
  return <mesh geometry={geometry} {...props} />
}

export function Bike(props) {
  const { nodes, materials } = useGLTF('/Blockout9-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Air Duct Rubber']} />
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Dark Steel']} />
      <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Dark Brown Leather']} />
      <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} />
      <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials.PaletteMaterial006} />
      <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.AppE8} />
      <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.AppED} />
      <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.AppCD} />
      <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Expanded Steel']} />
      <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.PaletteMaterial007} />
      <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials.PaletteMaterial008} />
    </group>
  )
}

export function Environment(props) {
  const { nodes, materials } = useGLTF('/Blockout9-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <Collidable name="ramp" geometry={nodes.ramp.geometry} material={materials.PaletteMaterial001} position={[17.835, 0.964, -25.903]} rotation={[0, 1.571, 0]} scale={[0.212, 0.088, 0.102]} />
      <mesh name="Tractor" geometry={nodes.Tractor.geometry} material={materials['Green matte metal']} position={[26.95, 1.633, 1.545]} rotation={[Math.PI / 2, 0, 1.591]} scale={0.039} />
      {/* <Collidable name="pavement001" geometry={nodes.pavement001.geometry} material={materials['Asphalt.002']} position={[3.656, 0.013, -0.058]} rotation={[0, 0.003, 0]} scale={[2.002, 1, 2.411]} /> */}
      <Collidable name="Skate_Park_Photoscan_2" geometry={nodes.Skate_Park_Photoscan_2.geometry} material={materials.skatepark_Sec2_u1_v1} position={[0.153, 0, 19.41]} rotation={[-Math.PI, 0.014, -Math.PI]} scale={1.161} />
      <Collidable name="Skate_Ramp_(Photoscanned)001" geometry={nodes['Skate_Ramp_(Photoscanned)001'].geometry} material={materials['Skate Ramp (Photoscanned)']} position={[13.366, 0, -27.865]} />
      <Collidable name="Skate_Ramp_(Photoscanned)" geometry={nodes['Skate_Ramp_(Photoscanned)'].geometry} material={materials.SkateRamp} position={[-7.578, 0, 28.091]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh name="Snowboard2" geometry={nodes.Snowboard2.geometry} material={materials.PaletteMaterial005} position={[-0.038, 1.268, -0.285]} rotation={[0.912, -0.011, 0.449]} scale={2.184} />
      <mesh name="Skateboard" geometry={nodes.Skateboard.geometry} material={materials.skateboard} position={[-2.227, 1.69, -12.139]} rotation={[0, -0.833, -1.386]} scale={2.133} />
      <mesh name="gogo_inflight" geometry={nodes.gogo_inflight.geometry} material={materials.PaletteMaterial004} position={[-12.163, 1.175, 19.319]} rotation={[1.34, -0.129, -2.639]} />
      <mesh name="FourKites" geometry={nodes.FourKites.geometry} material={materials.color} position={[17.312, 1.175, 12.084]} rotation={[1.695, 0.233, 1.076]} />
      {/* <Collidable name="floor_paint001" geometry={nodes.floor_paint001.geometry} material={materials.PaletteMaterial002} position={[-7.449, 0.018, 22.543]} /> */}
      <mesh name="box" geometry={nodes.box.geometry} material={materials.PaletteMaterial003} position={[30.295, 0, -17.997]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/Blockout9-transformed.glb')
